# Generated by Django 5.2.7 on 2025-10-24 20:03

import datetime
import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('saldo_atual_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3)),
                ('saldo_atual', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('saldo_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3)),
                ('saldo', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Recorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('valor_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3)),
                ('valor', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('periodicidade', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=10)),
                ('proxima_execucao', models.DateField(default=datetime.date.today)),
                ('recorrente_tipo', models.CharField(choices=[('assinatura', 'Assinatura'), ('parcela', 'Parcela'), ('conta', 'Conta'), ('financiamento', 'Financiamento')], default='assinatura', max_length=20)),
                ('parcela_total', models.PositiveIntegerField(blank=True, null=True)),
                ('parcela_atual', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrentes', to='a_core.categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrentes', to='a_core.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('valor_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3)),
                ('valor', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('realizado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='a_core.categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='a_core.conta')),
            ],
        ),
    ]
